/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import dao.Reparaciondao;
import vo.ReparacionVo;
import vo.trabajadorVo;

import javax.swing.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author David
 */
public class ventanaPrincipal extends javax.swing.JFrame {
    private String FF="";
    /**
     * Creates new form ventanaPrincipal
     */
    public ventanaPrincipal() {
        initComponents();
        construirTabla();
        construirTabla2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idspinner = new javax.swing.JSpinner();
        descripcion = new javax.swing.JTextField();
        horas = new javax.swing.JSpinner();
        precio = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        Apellido = new javax.swing.JTextField();
        dni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        insert = new javax.swing.JButton();
        modifica = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        finRep = new javax.swing.JButton();
        fechaFin = new javax.swing.JTextField();
        finicio = new javax.swing.JSpinner();
        consultar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        PrecioTot = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        direcc = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        borracasillas = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        idtrab = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        idtra = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        consultra = new javax.swing.JButton();
        insertra = new javax.swing.JButton();
        modifitra = new javax.swing.JButton();
        eliminatra = new javax.swing.JButton();
        reporte2 = new javax.swing.JButton();
        reporte1 = new javax.swing.JButton();
        reporte3 = new javax.swing.JButton();
        reporte4 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        reporte5 = new javax.swing.JButton();
        dnireporte = new javax.swing.JTextField();
        spinerfinireporte = new javax.swing.JSpinner();
        spinerffinreporte = new javax.swing.JSpinner();
        idtrabreporte = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idspinner.setModel(new javax.swing.SpinnerNumberModel());

        horas.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));
        horas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                horasStateChanged(evt);
            }
        });

        precio.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));
        precio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                precioStateChanged(evt);
            }
        });

        jLabel1.setText("Id trabajador");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel4.setText("DNI");

        jLabel5.setText("Descripción");

        jLabel6.setText("Horas");

        jLabel7.setText("Precio material");

        jLabel8.setText("F.Inicio");

        jLabel9.setText("F.Fin");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        insert.setText("Inserta");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    insertActionPerformed(evt);
                } catch (ParseException e) {
                    e.printStackTrace();
                }
            }
        });

        modifica.setText("Modifica");
        modifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificaActionPerformed(evt);
            }
        });

        jButton3.setText("Borra");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        finRep.setText("Finaliza rep");
        finRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finRepActionPerformed(evt);
            }
        });

        fechaFin.setEditable(false);

        finicio.setModel(new javax.swing.SpinnerDateModel());
        finicio.setEditor(new javax.swing.JSpinner.DateEditor(finicio, "dd-MM-yyyy"));

        consultar.setText("Consultar");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    consultarActionPerformed(evt);
                } catch (ParseException e) {
                    e.printStackTrace();
                }
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mecánica", "Chapa y pintura", "Revisión" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Tipo Reparación");

        jLabel11.setText("Precio total");

        PrecioTot.setEditable(false);

        jLabel13.setText("Dirección");

        jLabel14.setText("Teléfono");

        direcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccActionPerformed(evt);
            }
        });

        borracasillas.setText("Borra casillas");
        borracasillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borracasillasActionPerformed(evt);
            }
        });

        jLabel15.setText("Id");

        idtrab.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel16.setText("TRABAJADOR");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setText("REPARACIÓN");

        jLabel18.setText("id del trab");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        consultra.setText("Consulta");
        consultra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultraActionPerformed(evt);
            }
        });

        insertra.setText("Inserta");
        insertra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertraActionPerformed(evt);
            }
        });

        modifitra.setText("Modifica");
        modifitra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifitraActionPerformed(evt);
            }
        });

        eliminatra.setText("Elimina");
        eliminatra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminatraActionPerformed(evt);
            }
        });

        reporte2.setText("Trabajadores");
        reporte2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporte2ActionPerformed(evt);
            }
        });

        reporte1.setText("Reparaciones");
        reporte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporte1ActionPerformed(evt);
            }
        });

        reporte3.setText("Trabajador");
        reporte3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporte3ActionPerformed(evt);
            }
        });

        reporte4.setText("Reparación por fecha");
        reporte4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporte4ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Informes");

        reporte5.setText("Reparación por Operario");
        reporte5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporte5ActionPerformed(evt);
            }
        });

        spinerfinireporte.setModel(new javax.swing.SpinnerDateModel());
        spinerfinireporte.setEditor(new javax.swing.JSpinner.DateEditor(spinerfinireporte, "dd-MM-yyyy"));

        spinerffinreporte.setModel(new javax.swing.SpinnerDateModel());
        spinerffinreporte.setEditor(new javax.swing.JSpinner.DateEditor(spinerffinreporte, "dd-MM-yyyy"));

        jLabel20.setText("DNI:");

        jLabel21.setText("Fecha inicio/fin");

        jLabel22.setText("id trabajador:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel13))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(direcc, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(87, 87, 87)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(idtra)
                                        .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))))
                            .addGap(104, 104, 104))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel11))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(horas)
                                                    .addComponent(precio)
                                                    .addComponent(descripcion)
                                                    .addComponent(fechaFin)
                                                    .addComponent(finicio)
                                                    .addComponent(PrecioTot, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel15))
                                        .addComponent(idtrab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(idspinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(consultra)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(insertra)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(modifitra)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(eliminatra))
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(finRep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(borracasillas))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(consultar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(insert)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modifica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)))
                        .addGap(72, 72, 72)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(reporte1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reporte2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reporte3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reporte4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reporte5, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dnireporte, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idtrabreporte, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spinerfinireporte, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(spinerffinreporte, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(direcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(consultra)
                            .addComponent(insertra)
                            .addComponent(modifitra)
                            .addComponent(eliminatra)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(idspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(idtrab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(horas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(finicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(fechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(PrecioTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insert)
                            .addComponent(modifica)
                            .addComponent(jButton3)
                            .addComponent(consultar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(finRep)
                            .addComponent(borracasillas))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reporte1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reporte2))
                            .addComponent(jLabel19)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(reporte3)
                                    .addComponent(jLabel20)
                                    .addComponent(dnireporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(reporte4)
                                    .addComponent(jLabel21)
                                    .addComponent(spinerfinireporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinerffinreporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(reporte5)
                                    .addComponent(idtrabreporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22))))
                        .addGap(0, 16, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertActionPerformed(java.awt.event.ActionEvent evt) throws ParseException {//GEN-FIRST:event_insertActionPerformed
        String fechafin;
        SimpleDateFormat date;
        date = new SimpleDateFormat("yyyy-MM-dd");
        ReparacionVo repa = new ReparacionVo();
        repa.setId_tra((Integer) idtrab.getValue());
        repa.setTiporep(String.valueOf(jComboBox1.getSelectedItem()));
        repa.setDescripcion(descripcion.getText());
        repa.setHoras((Double)horas.getValue());
        repa.setPrecio((Double)precio.getValue());
        repa.setfInicio(date.format(finicio.getValue()));
        if(fechaFin.getText().equals("")){
             FF=null;
        }else{

            System.out.println(FF);
        }

        repa.setfFin(FF);
        try {
            repa.setPrecio_tot(Double.valueOf(PrecioTot.getText()));
            Reparaciondao re = new Reparaciondao();
            re.insertar(repa);
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Campos vacios obligatorios", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        construirTabla();
        vacio();

    }//GEN-LAST:event_insertActionPerformed

    private void precioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_precioStateChanged
         String tipo="";
        Double valor;
        Double prec ;
        Double preciHora;
        preciHora=((Double)horas.getValue())*30;
        tipo=jComboBox1.getSelectedItem()+"";

        if(tipo.equals("Mecánica")){
            valor=1.5;
            prec= (Double) precio.getValue();

            prec=prec*valor+preciHora;
            PrecioTot.setText(prec+"");


        }else if(tipo.equals("Chapa y pintura")){
            valor =2.0;
            prec= (Double) precio.getValue();
            prec=prec*valor+preciHora;
            PrecioTot.setText(prec+"");

        }else if(tipo.equals("Revisión")){
            valor =20.00;
            prec=preciHora+valor;
            PrecioTot.setText(prec+"");
        }
    }//GEN-LAST:event_precioStateChanged

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) throws ParseException {//GEN-FIRST:event_consultarActionPerformed
            try {
                SimpleDateFormat date;
                date = new SimpleDateFormat("dd-MM-yyyy");
                Reparaciondao re = new Reparaciondao();
                ReparacionVo repa = new ReparacionVo();
                repa = (re.Consulta((int) idspinner.getValue()));
                idtra.setValue(repa.getId_tra());
                jComboBox1.setSelectedItem(repa.getTiporep());
                descripcion.setText(repa.getDescripcion());
                horas.setValue(repa.getHoras());
                precio.setValue(repa.getPrecio());
                finicio.setValue(date.parse(repa.getfInicio()));//convertimos el string a date para que aparezca en el spinner
                fechaFin.setText(repa.getfFin());
                PrecioTot.setText(String.valueOf(repa.getPrecio_tot()));
            }catch (NullPointerException e){
                JOptionPane.showMessageDialog(null, "El id consultado no existe", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }



    }//GEN-LAST:event_consultarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
         String tipo="";
        Double valor;
        Double prec ;
        Double preciHora;
        preciHora=((Double)horas.getValue())*30;
        tipo=jComboBox1.getSelectedItem()+"";

        if(tipo.equals("Mecánica")){
            valor=1.5;
            prec= (Double) precio.getValue();

            prec=prec*valor+preciHora;
            PrecioTot.setText(prec+"");


        }else if(tipo.equals("Chapa y pintura")){
            valor =2.0;
            prec= (Double) precio.getValue();
            prec=prec*valor+preciHora;
            PrecioTot.setText(prec+"");

        }else if(tipo.equals("Revisión")){
            valor =20.00;
            prec=preciHora+valor;
            PrecioTot.setText(prec+"");
        }
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void horasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_horasStateChanged
        String tipo="";
        Double valor;
        Double prec ;
        Double preciHora;
        preciHora=((Double)horas.getValue())*30;
        tipo=jComboBox1.getSelectedItem()+"";

        if(tipo.equals("Mecánica")){
            valor=1.5;
            prec= (Double) precio.getValue();

            prec=prec*valor+preciHora;
            PrecioTot.setText(prec+"");


        }else if(tipo.equals("Chapa y pintura")){
            valor =2.0;
            prec= (Double) precio.getValue();
            prec=prec*valor+preciHora;
            PrecioTot.setText(prec+"");

        }else if(tipo.equals("Revisión")){
            valor =20.00;
            prec=preciHora+valor;
            PrecioTot.setText(prec+"");
        }
    }//GEN-LAST:event_horasStateChanged

    private void direccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccActionPerformed

    private void finRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finRepActionPerformed
        if(fechaFin.getText().equals("")){
            SimpleDateFormat date;
            SimpleDateFormat date2;
            date = new SimpleDateFormat("dd-MM-yyyy");
            Date objDate = new Date();
            //date.format(objDate);
            fechaFin.setText(date.format(objDate));
            date2 = new SimpleDateFormat("yyyy-MM-dd");
            FF=(date2.format(objDate));

        }else{

        }

    }//GEN-LAST:event_finRepActionPerformed

    private void modificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificaActionPerformed
       Reparaciondao repa = new Reparaciondao();
        ReparacionVo re;
            re = repa.Consulta((Integer) idspinner.getValue());
            SimpleDateFormat date;
            date = new SimpleDateFormat("yyyy-MM-dd");
            re.setfInicio(date.format(finicio.getValue()));
            if(re.getfFin().equals("")){
           re.setTiporep(String.valueOf(jComboBox1.getSelectedItem()));
           re.setDescripcion(descripcion.getText());
           re.setHoras((Double)horas.getValue());
           re.setPrecio((Double)precio.getValue());
           re.setfInicio(date.format(finicio.getValue()));
           if(fechaFin.getText().equals("")){
               FF=null;
           }else{

               System.out.println(FF);
           }
            try {
                re.setfFin(FF);
                re.setPrecio_tot(Double.valueOf(PrecioTot.getText()));

                repa.modifica(re);
            }catch (NumberFormatException e){

                JOptionPane.showMessageDialog(null, "Ha ocurrido un error", "Error",
                        JOptionPane.ERROR_MESSAGE);

            }
       }else {
           JOptionPane.showMessageDialog(null, "La reparacion ya está finalizada", "Error",
                   JOptionPane.ERROR_MESSAGE);
       }

        construirTabla();
       construirTabla2();
    }//GEN-LAST:event_modificaActionPerformed

    private void borracasillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borracasillasActionPerformed
        vacio();
    }//GEN-LAST:event_borracasillasActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Reparaciondao repa = new Reparaciondao();
        repa.Consulta((Integer) idspinner.getValue());
        repa.elimina((Integer) idspinner.getValue());
        construirTabla();




    }//GEN-LAST:event_jButton3ActionPerformed

    private void consultraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultraActionPerformed
        try {

            Reparaciondao re = new Reparaciondao();
            trabajadorVo repa;
            repa = (re.Consultatra((int) idtra.getValue()));
            nombre.setText(repa.getNombre());
            Apellido.setText(repa.getApellido());
            dni.setText(repa.getDni());
            direcc.setText(repa.getDireccion());
            telefono.setText(repa.getTelefono());

        }catch (NullPointerException e){
            JOptionPane.showMessageDialog(null, "El id consultado no existe", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_consultraActionPerformed

    private void insertraActionPerformed(java.awt.event.ActionEvent evt) {                                                          

        Reparaciondao dao = new Reparaciondao();
        trabajadorVo repa = new trabajadorVo();
        //repa.setId((Integer) idtra.getValue());
        repa.setNombre(nombre.getText());
        repa.setApellido(Apellido.getText());
        repa.setDni(dni.getText());
        repa.setDireccion(direcc.getText());
        repa.setTelefono(telefono.getText());
        dao.insertartrab(repa);
        construirTabla();
        construirTabla2();
        vacio();
    }                                        

    private void modifitraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifitraActionPerformed
        Reparaciondao repa = new Reparaciondao();
        trabajadorVo re;

        re = repa.Consultatra((Integer)idtra.getValue());

            try {
                re.setNombre(nombre.getText());
                re.setApellido(Apellido.getText());
                re.setDni(dni.getText());
                re.setDireccion(direcc.getText());
                re.setTelefono(telefono.getText());

                repa.modificatra(re);
            }catch (NumberFormatException e){

                JOptionPane.showMessageDialog(null, "Ha ocurrido un error", "Error",
                        JOptionPane.ERROR_MESSAGE);

            }

        construirTabla();
        construirTabla2();
    }//GEN-LAST:event_modifitraActionPerformed

    private void eliminatraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminatraActionPerformed
        Reparaciondao repa = new Reparaciondao();
        repa.Consulta((Integer) idtra.getValue());
        repa.eliminatra((Integer) idtra.getValue());
        construirTabla();
        construirTabla2();
    }//GEN-LAST:event_eliminatraActionPerformed

    private void reporte5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporte5ActionPerformed
        Reparaciondao repor = new Reparaciondao();

        repor.reporteoper( idtrabreporte.getValue()+"");
    }//GEN-LAST:event_reporte5ActionPerformed

    private void reporte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporte1ActionPerformed
        Reparaciondao repor = new Reparaciondao();
        repor.reportereparaciones();
    }//GEN-LAST:event_reporte1ActionPerformed

    private void reporte2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporte2ActionPerformed
        Reparaciondao repor = new Reparaciondao();
        repor.reporteTrabjadores();
    }//GEN-LAST:event_reporte2ActionPerformed

    private void reporte3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporte3ActionPerformed
        Reparaciondao repor = new Reparaciondao();
        repor.reporteDni(dnireporte.getText());
    }//GEN-LAST:event_reporte3ActionPerformed

    private void reporte4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporte4ActionPerformed
        Reparaciondao repor = new Reparaciondao();
        SimpleDateFormat date;
        String ini;
        String fin;
        date = new SimpleDateFormat("yyyy-MM-dd");
        ini=date.format(spinerfinireporte.getValue());
        fin=date.format(spinerfinireporte.getValue());
        repor.repotefechas(ini,fin);


    }//GEN-LAST:event_reporte4ActionPerformed



    private void construirTabla() {

        String titulos[]={ "Id", "id_trab","tipo_rep","Descripcion","Horas","Precio","Fecha_ini","Fecha_fin","Precio_tot" };
        String informacion[][]=obtenerDatos();

        tabla=new JTable(informacion,titulos);

        jScrollPane1.setViewportView(tabla);


    }

    private void construirTabla2() {

        String titulos[]={ "Id_trab", "Nombre", "Apellido", "DNI", "Direccion","Telefono"};
        String informacion[][]=obtenerDatos2();

        jTable1=new JTable(informacion,titulos);

        jScrollPane2.setViewportView(jTable1);


    }

    private String[][] obtenerDatos() {

        Reparaciondao repa = new Reparaciondao();
        ArrayList<ReparacionVo> miLista = repa.obtenDatos();

        String Datos[][]=new String[miLista.size()][9];

        for (int i = 0; i < miLista.size(); i++) {
            Datos[i][0]=miLista.get(i).getId()+"";
            Datos[i][1]=miLista.get(i).getId_tra()+"";
            Datos[i][2]=miLista.get(i).getTiporep()+"";
            Datos[i][3]=miLista.get(i).getDescripcion()+"";
            Datos[i][4]=miLista.get(i).getHoras()+"";
            Datos[i][5]=miLista.get(i).getPrecio()+"";
            Datos[i][6]=miLista.get(i).getfInicio()+"";
            Datos[i][7]=miLista.get(i).getfFin()+"";
            Datos[i][8]=miLista.get(i).getPrecio_tot()+"";
        }

        return Datos;
    }

    private String[][] obtenerDatos2() {

        Reparaciondao repa = new Reparaciondao();
        ArrayList<trabajadorVo> miLista = repa.obtenDatostra();

        String Datos[][]=new String[miLista.size()][6];

        for (int i = 0; i < miLista.size(); i++) {
            Datos[i][0]=miLista.get(i).getId()+"";
            Datos[i][1]=miLista.get(i).getNombre()+"";
            Datos[i][2]=miLista.get(i).getApellido()+"";
            Datos[i][3]=miLista.get(i).getDni()+"";
            Datos[i][4]=miLista.get(i).getDireccion()+"";
            Datos[i][5]=miLista.get(i).getTelefono()+"";

        }

        return Datos;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido;
    private javax.swing.JTextField PrecioTot;
    private javax.swing.JButton borracasillas;
    private javax.swing.JButton consultar;
    private javax.swing.JButton consultra;
    private javax.swing.JTextField descripcion;
    private javax.swing.JTextField direcc;
    private javax.swing.JTextField dni;
    private javax.swing.JTextField dnireporte;
    private javax.swing.JButton eliminatra;
    private javax.swing.JTextField fechaFin;
    private javax.swing.JButton finRep;
    private javax.swing.JSpinner finicio;
    private javax.swing.JSpinner horas;
    private javax.swing.JSpinner idspinner;
    private javax.swing.JSpinner idtra;
    private javax.swing.JSpinner idtrab;
    private javax.swing.JSpinner idtrabreporte;
    private javax.swing.JButton insert;
    private javax.swing.JButton insertra;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modifica;
    private javax.swing.JButton modifitra;
    private javax.swing.JTextField nombre;
    private javax.swing.JSpinner precio;
    private javax.swing.JButton reporte1;
    private javax.swing.JButton reporte2;
    private javax.swing.JButton reporte3;
    private javax.swing.JButton reporte4;
    private javax.swing.JButton reporte5;
    private javax.swing.JSpinner spinerffinreporte;
    private javax.swing.JSpinner spinerfinireporte;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables

    public void vacio(){
        nombre.setText("");
        Apellido.setText("");
        dni.setText("");
        direcc.setText("");
        telefono.setText("");
        descripcion.setText("");
        horas.setValue(0.0);
        precio.setValue(0.0);
        fechaFin.setText("");
        PrecioTot.setText("");

    }
}

